version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    ports:
      - 5050:5050
    env_file:
      - .env

  # backend_app:
  #   container_name: backend_app
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./backend/
  #   environment:
  #     - ENVIRONMENT=${ENVIRONMENT}
  #   volumes:
  #     - ./backend/:/usr/backend/
  #   expose:
  #     - 8000
  #   ports:
  #     - 8001:8000
  #   depends_on:
  #     - db

volumes:
  app-db-data:
