"""add player table

Revision ID: e784f0db5146
Revises: 1f674ec3dca5
Create Date: 2023-07-19 00:58:39.707250

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "e784f0db5146"
down_revision = "1f674ec3dca5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
